version: '3.8'
services:
  api:
    image: student_api  # Nom de l'image que vous avez construite précédemment pour l'API
    container_name: student_api_container
    volumes:
      - ./simple_api/student_age.json:/data/student_age.json
    ports:
      - "5000:5000"  # Exposer le port 5000 de l'API
    networks:
      - student_network  # Utilisation d'un réseau spécifique pour l'application
    environment:
      - FLASK_APP=student_age
      - FLASK_ENV=development
    restart: always
  website:
    image: php:apache  # Utilisation de l'image php:apache pour l'interface utilisateur
    container_name: website_container
    environment:
      - USERNAME=root
      - PASSWORD=root
    volumes:
      - ./website:/var/www/html  # Lier le répertoire 'website' local au répertoire '/var/www/html' dans le conteneur
    depends_on:
      - api  # L'API doit démarrer avant le site web
    ports:
      - "8080:80"  # Exposer le port 80 du site web sur le port 8080 de l'hôte
    networks:
      - student_network  # Utiliser le même réseau que l'API
    restart: always
networks:
  student_network:  # Définir un réseau spécifique pour le projet
    driver: bridge